processing-common/dlq/doc/SRN.md

Correction on chariot returns
highlight properties 
Set example between bash tags

Minor typo changes

---

processing-common/doc/README.md

To be coherent with error.md page title

Change url link of error.md

---

processing-common/dlq/doc/ReleaseNote.md

I propose 0 as minimum value. Does the code accept negative value?
I propose 2147483647 (java max int) as maximum value. Does the code apply an other limit?

Add priority min/max  ReleaseNote.md

---

rs-container/docker_s3_ipf_sm2_si/Dockerfile

Base image was Land Ice and not See Ice as expected

Correct sm2_si dockerfile

---

rs-container/docker_s1_ipf_l1/Dockerfile

Test if the proposed WA in [COPRS/rs-issues#815 
[[BUG][L1] PSC_PreprocMain segfault error](https://app.zenhub.com/workspaces/ccb-board-61b0d5b7cccfc20017832c22/issues/gh/coprs/rs-issues/815)](https://github.com/COPRS/rs-issues/issues/815) works

RS-815 Change S1-L1 USER in dockerfile #IPF

---

rs-container/docker_s1_ipf_l1/Dockerfile

Update S1 L1 from develop in order to test the WA image 3.6.1-light for S1-L1 
Do not contain mask update

#IPF RS-885 Update to S1 L1 3.6.1-light

---

processing-common/ingestion/doc/ReleaseNote.md

Remove 's' 
production-common/blob/develop/processing-common/doc/secrets.md => production-common/blob/develop/processing-common/doc/secret.md

Update secret.md url in Ingestion/doc/ReleaseNote.md

---

processing-common/doc/buckets.md
rs-libs/obs-sdk/src/main/java/esa/s1pdgs/cpoc/obs_sdk/ObsConfigurationProperties.java
rs-libs/obs-sdk/src/test/resources/obs-aws-s3.properties

Related to : 
- [BUG] Many connection refused for RS CORE compression #1015
Multiple per 12 the throttled-base-delay (period between two retries) 
Part 1 - documentation

Update doc for  throttled-base-delay (buckets.md )

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Test build #IPF  S1 /L2 with anchore versiont 3 

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Deactivate option no mored used anchore v3
and critical step (not used to stop build)

#IPF S1 L1/L2 build with deactivate option no more used on v3

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

#IPF S1 L1/L2 build update codeql-action in v3

#IPF S1 L1/L2 build update codeql-action in v3

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Uncoment report generation, back to v2 for upload report and ad…d inspect SARIF STEP

#IPF Uncoment report generation, v2 for upload report, add log on report 

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Use inspect step before uploading SARIF file and force #IPF S1 L1 L2 build

Use inspect step before uploading SARIF file and force #IPF S1 L1 L2 build

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Update this to force build a,d test upload-artifact updated version

Test update anchore versiontestbuild #IPF

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Update json path according to anchore v3 and force build #IPF

Update json path according to anchore v3 and force build #IPF

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

#IPF Remove Inspect and upload step no more used

#IPF Remove Inspect and upload step no more used

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

#IPF Revert to Anchore v2 configuration (keep old generic configuration for all build)

#IPF Revert to Anchore v2 configuration (keep old generic configuration for all build)

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

Force Build with new IPF container #IPF

Force Build with new IPF container #IPF

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile
rs-container/docker_s1_ipf_l2/Dockerfile

#IPF Deactivate SARIF format for activate only json one
Change SARIF to JSON
Activate upload-artifact for this file
Deactivate SARIF-Report upload
Activate Docker build on S1 L1 L2

#IPF Deactivate SARIF format for activate only json one

---

.github/actions/build-ipf-container/action.yaml
rs-container/docker_s1_ipf_l1/Dockerfile

Inspect JSON Report 
Force build on S1 L1

#IPF Add Inspect SCAN Report JSON 
